version: '3.8'

services:
  web:
    build: .
    container_name: photo_voting_app
    restart: unless-stopped
    ports:
      - "5050:5050"
    working_dir: /usr/src/app  # Hier wird das Arbeitsverzeichnis gesetzt
    environment:
      - FLASK_APP=run.py
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=5050
    # Vermeide das Volume-Mount für das Projektverzeichnis, wenn du den gesamten Code im Dockerfile kopierst
    # volumes:
    #   - ./app:/usr/src/app  # Falls du das brauchst, musst du sicherstellen, dass die Struktur korrekt ist
    command: /bin/bash -c "./start.sh"  # Startet das Skript aus dem richtigen Pfad