version: '3.8'

services:
  web:
    image: python:3.12
    container_name: photo_voting_app
    restart: unless-stopped
    ports:
      - "5050:5050"
    working_dir: /usr/src/app
    volumes:
      - ./app:/usr/src/app
      - ./env/.env:/usr/src/app/.env
    environment:
      - FLASK_APP=run.py
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=5050
    command: |
      /bin/bash -c "
      if [ ! -d .git ]; then
        git clone https://github.com/MinhMTV/Photo_Voting_Contest.git .;
      fi &&
      git pull &&

      if [ ! -f .env ]; then
        echo 'FLASK_APP=run.py' > .env &&
        echo 'FLASK_ENV=production' >> .env &&
        echo 'FLASK_RUN_HOST=0.0.0.0' >> .env &&
        echo 'FLASK_RUN_PORT=5050' >> .env &&
        echo 'ADMIN_PASSWORD=changeme' >> .env &&
        echo 'SECRET_KEY=changeme' >> .env
      fi &&

      pip install --upgrade pip &&
      pip install -r requirements.txt &&
      flask run
      "