version: '3.8'

services:
  web:
    build: .
    container_name: photo_voting_app
    restart: unless-stopped
    ports:
      - "5050:5050"
    working_dir: /usr/src/app  # Hier wird das Arbeitsverzeichnis gesetzt