version: '3.8'

services:
  web:
    build: .
    container_name: photo_voting_app
    restart: unless-stopped
    ports:
      - "5050:5050"
    volumes:
      - ./app:/usr/src/app  # Hier sicherstellen, dass das Verzeichnis korrekt gemountet wird.
    working_dir: /usr/src/app  # Stelle sicher, dass dies dem Arbeitsverzeichnis entspricht
    environment:
      - FLASK_APP=run.py
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=5050
    command: /bin/bash -c "./start.sh"