version: '3.8'

services:
  web:
    image: python:3.12
    container_name: photo_voting_app
    restart: unless-stopped
    ports:
      - "5050:5050"
    volumes:
      - ./app:/usr/src/app
    working_dir: /usr/src/app
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=development
    command: /bin/bash -c "
      if [ ! -d .git ]; then
        git clone https://github.com/MinhMTV/Photo_Voting_Contest.git .;
      fi &&
      git pull &&
      pip install --upgrade pip &&
      pip install -r requirements.txt &&
      flask run --host=0.0.0.0
    "